apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: backend
          image: 172.22.174.102:5000/mlops-backend:latest
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: COMET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: anime-app-secrets
                  key: comet-api-key
          volumeMounts:
            - name: gcp-sa
              mountPath: /var/secrets/google
              readOnly: true
      volumes:
        - name: gcp-sa
          secret:
            secretName: gcp-service-account